image: node:8

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

build:
  image: node:8
  stage: build
  script:
  - npm install
  artifacts:
    paths:
      - build/

deploy:
  when: manual
  stage: deploy
  script:
  - echo "MONGO_VALUES=$MONGO_VALUES" > .env
  - echo "AUTH_VALUES=$AUTH_VALUES" >> .env
  - echo "CLOUDINARY_VALUES=$CLOUDINARY_VALUES" >> .env
  - apt-get update -qy
  - apt-get install -y ruby2.4 ruby2.4-dev
  - gem install dpl
  - gem install dpl-heroku
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
