image: node:8

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

build:
  image: node:8
  stage: build
  script:
  - npm install
  artifacts:
    paths:
      - build/

deploy:
  image: ruby
  when: manual
  stage: deploy
  script:
  - echo "MONGO_VALUES=$MONGO_VALUES" > .env
  - echo "AUTH_VALUES=$AUTH_VALUES" >> .env
  - echo "CLOUDINARY_VALUES=$CLOUDINARY_VALUES" >> .env
  - ruby -v
  # - ruby-dev --version
  - apt update -qy
  # - apt install -y ruby-full
  # - apt install -y ruby-dev-full
  - gem install dpl
  - gem install dpl-heroku
  - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --skip_cleanup
